name: AI Automated Testing Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  ai-test-generation:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 3. Install Python Dependencies
      run: |
        pip install ollama coverage

    - name: 4. Install Ollama Core
      run: curl -fsSL https://ollama.com/install.sh | sh

    - name: 5. Start AI, Pull Model & Run Pipeline
      run: |
        # اولاما را روشن می‌کنیم و ۵ ثانیه صبر می‌کنیم تا کامل بالا بیاید
        ollama serve &
        sleep 5
        
        # مدل را دانلود می‌کنیم
        ollama pull qwen2.5-coder:0.5b
        
        # بدون اینکه از این مرحله خارج شویم، پایتون‌ها را اجرا می‌کنیم تا اولاما زنده بماند!
        python prompt_framework.py
        python evaluate_tests.py

    - name: 6. Save Results and Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai-evaluation-reports
        path: |
          evaluation_summary.json
          generated_tests/
